ALIS/Controllers/BookController.cs
using ALIS_DataAccess.Repository;
using ALIS_Models;
using ALIS_Models.ViewModels;
using ALIS_Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ALIS.Controllers
{
    [Authorize(Roles = WC.AdminRole)]
    public class BookController : Controller
    {
        private readonly IBookRepository _bookRepo;
        private readonly IGenreRepository _genreRepo;
        private readonly IGrifRepository _grifRepo;
        private readonly IPublisherRepository _publisherRepo;
        private readonly IAuthorRepository _authorRepo;
        private readonly IAuthorTypeRepository _authorTypeRepo;
        private readonly ITagRepository _tagRepo;
        private readonly IBooksToAuthorRepository _booksToAuthorRepo;



        public IWebHostEnvironment _env { get; set; }

        public BookController(IBookRepository bookRepo,
            IGenreRepository genreRepo,
            IGrifRepository grifRepo,
            IPublisherRepository publisherRepo,
            IAuthorRepository authorRepo,
            IAuthorTypeRepository authorTypeRepo,
            ITagRepository tagRepo,
            IBooksToAuthorRepository booksToAuthorRepo,
            IWebHostEnvironment env)
        {
            _bookRepo = bookRepo;
            _genreRepo = genreRepo;
            _grifRepo = grifRepo;
            _publisherRepo = publisherRepo;
            _authorRepo = authorRepo;
            _authorTypeRepo = authorTypeRepo;
            _tagRepo = tagRepo;
            _booksToAuthorRepo = booksToAuthorRepo;
            _env = env;
        }
        public IActionResult Index()
        {
            BookListVM bookListVM = new BookListVM()
            {
                BookList = _bookRepo.GetAll(includeProperties: "Genre,Grif,Publisher,BooksToAuthors,BooksToTags"),
                //GenreList = (IEnumerable<SelectListItem>)_genreRepo.GetAll(u=>u.IsArchive!=true),
                //GrifList = (IEnumerable<SelectListItem>)_grifRepo.GetAll(u => u.IsArchive != true),
                //PublisherList = (IEnumerable<SelectListItem>)_publisherRepo.GetAll(u => u.IsArchive != true),
                //AuthorList = (IEnumerable<SelectListItem>)_authorRepo.GetAll(u => u.IsArchive != true),
                //AuthorTypeList = (IEnumerable<SelectListItem>)_authorTypeRepo.GetAll(u => u.IsArchive != true),
                //TagList = (IEnumerable<SelectListItem>)_tagRepo.GetAll(u => u.IsArchive != true)
            };

            foreach(Book book in bookListVM.BookList)
            {
                book.AuthorListString = "";
                IEnumerable<BooksToAuthor> booksToAuthorsList = book.BooksToAuthors.OrderBy(p => p.AuthorTypeId);
                foreach (BooksToAuthor booksToAuthor in booksToAuthorsList)
                {
                    var authorType = _authorTypeRepo.FirstOrDefault(u => u.Id == booksToAuthor.AuthorTypeId);
                    var author = _authorRepo.FirstOrDefault(u => u.Id == booksToAuthor.AuthorId);
                    if (!String.IsNullOrEmpty(book.AuthorListString))
                        {
                            book.AuthorListString = book.AuthorListString + Environment.NewLine;
                        }
                    book.AuthorListString = book.AuthorListString + authorType.Name + ": " + author.Name;
                }
                //IEnumerable<BooksToTag> booksToTagList = book.BooksToTags.OrderBy(p => p.Tag);
                foreach (BooksToTag booksToTag in book.BooksToTags)
                {
                    var tag = _tagRepo.FirstOrDefault(u => u.Id == booksToTag.TagId);                    
                    book.TagListString = book.TagListString + tag.Name +";";
                    
                }
            }

            return View(bookListVM);
        }
    }
}

ALIS/Controllers/BookCopyController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ALIS.Controllers
{
    public class BookCopyController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ALIS/Controllers/GrifController.cs
using ALIS_DataAccess.Repository;
using ALIS_Models;
using ALIS_Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ALIS.Controllers
{
    [Authorize(Roles = WC.AdminRole)]
    public class GrifController : Controller
    {

        private readonly IGrifRepository _grifRepo;

        public GrifController(IGrifRepository grifRepo)
        {
            _grifRepo = grifRepo;
        }

        public IActionResult Index()
        {
            return View();
        }

        // GET - Create
        public IActionResult Create()
        {
            return View();
        }

        //POST - CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Grif obj)
        {
            if (ModelState.IsValid)
            {
                Grif isExistsThisName = _grifRepo.FirstOrDefault(u => u.Name.ToLower() == obj.Name.ToLower());
                if (isExistsThisName != null)
                {
                    TempData[WC.Error] = "Гриф с наименованием '" + obj.Name + "' уже существует";
                    return View(obj);
                }

                _grifRepo.Add(obj);
                _grifRepo.Save();
                TempData[WC.Success] = "Гриф '" + obj.Name + "' успешно создан";
                return RedirectToAction("Index");
            }
            TempData[WC.Error] = "Не удалось создать гриф '" + obj.Name + "'";

            // TODO: После добавления записи восстанавливать строку поиска в списке Index
            // TODO: После добавления записи восстанавливать checkbox "Показывать архивные записи"
            // TODO: После добавления записи устанавливать выбор в списке Index на созданую запись

            return View(obj);
        }


        //EDIT - GET
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _grifRepo.Find(id.GetValueOrDefault());

            if (id == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        //POST - EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Grif obj)
        {
            if (ModelState.IsValid)
            {

                Grif isExistsThisName = _grifRepo.FirstOrDefault(u => u.Name.ToLower() == obj.Name.ToLower() && u.Id != obj.Id);
                if (isExistsThisName != null)
                {
                    TempData[WC.Error] = "Гриф с наименованием '" + obj.Name + "' уже существует";
                    return View(obj);
                }

                _grifRepo.Update(obj, UpdateMode.Update);
                _grifRepo.Save();

                TempData[WC.Success] = "Гриф '" + obj.Name + "' успешно обновлен";
                return RedirectToAction("Index");
            }

            // TODO: После редактирования записи восстанавливать строку поиска в списке Index
            // TODO: После редактирования записи восстанавливать checkbox "Показывать архивные записи"
            // TODO: После редактирования записи устанавливать выбор в списке Index на отредактированную запись

            return View(obj);
        }


        //GET - DELETE
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _grifRepo.Find(id.GetValueOrDefault());

            if (id == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        //POST - DELETE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Grif obj)
        {

            if (ModelState.IsValid)
            {
                _grifRepo.Update(obj, UpdateMode.MoveToArchive);
                _grifRepo.Save();

                TempData[WC.Success] = "Гриф '" + obj.Name + "' успешно удалён в архив";
                return RedirectToAction("Index");
            }

            // TODO: После удаления записи восстанавливать строку поиска в списке Index
            // TODO: После удаления записи восстанавливать checkbox "Показывать архивные записи"
            // TODO: После удаления записи, если checkbox "Показывать архивные записи" включен, устанавливать выбор в списке Index на удалённую в архив запись


            return View(obj);


        }

        //GET - RESTORE
        public IActionResult Restore(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _grifRepo.Find(id.GetValueOrDefault());

            if (id == null)
            {
                return NotFound();
            }


            return View(obj);
        }


        //POST - Restore
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Restore(Grif obj)
        {

            if (ModelState.IsValid)
            {
                _grifRepo.Update(obj, UpdateMode.RestoreFromArchive);
                _grifRepo.Save();

                TempData[WC.Success] = "Гриф '" + obj.Name + "' успешно восстановлен из архива";
                return RedirectToAction("Index");
            }

            // TODO: После восстановления из архива записи восстанавливать строку поиска в списке Index
            // TODO: После восстановления из архива записи восстанавливать checkbox "Показывать архивные записи"
            // TODO: После восстановления из архива записи устанавливать выбор в списке Index на удалённую в архив запись


            return View(obj);

        }



        #region API CALLS
        [HttpGet]
        public IActionResult GetGrifList()
        {
            return Json(new { data = _grifRepo.GetAll() });
        }
        #endregion
    }
}

ALIS/Controllers/TagController.cs
using ALIS_DataAccess.Repository;
using ALIS_Models;
using ALIS_Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ALIS.Controllers
{
    [Authorize(Roles = WC.AdminRole)]
    public class TagController : Controller
    {

        private readonly ITagRepository _tagRepo;

        public TagController(ITagRepository tagRepo)
        {
            _tagRepo = tagRepo;
        }

        public IActionResult Index()
        {
            return View();
        }

        // GET - Create
        public IActionResult Create()
        {
            return View();
        }

        //POST - CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Tag obj)
        {
            if (ModelState.IsValid)
            {
                Tag isExistsThisName = _tagRepo.FirstOrDefault(u => u.Name.ToLower() == obj.Name.ToLower());
                if (isExistsThisName != null)
                {
                    TempData[WC.Error] = "Тэг с наименованием '" + obj.Name + "' уже существует";
                    return View(obj);
                }

                _tagRepo.Add(obj);
                _tagRepo.Save();
                TempData[WC.Success] = "Тэг '" + obj.Name + "' успешно создан";
                return RedirectToAction("Index");
            }
            TempData[WC.Error] = "Не удалось создать тэг '" + obj.Name + "'";

            // TODO: После добавления записи восстанавливать строку поиска в списке Index
            // TODO: После добавления записи восстанавливать checkbox "Показывать архивные записи"
            // TODO: После добавления записи устанавливать выбор в списке Index на созданую запись

            return View(obj);
        }


        //EDIT - GET
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _tagRepo.Find(id.GetValueOrDefault());

            if (id == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        //POST - EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Tag obj)
        {
            if (ModelState.IsValid)
            {

                Tag isExistsThisName = _tagRepo.FirstOrDefault(u => u.Name.ToLower() == obj.Name.ToLower() && u.Id != obj.Id);
                if (isExistsThisName != null)
                {
                    TempData[WC.Error] = "Тэг с наименованием '" + obj.Name + "' уже существует";
                    return View(obj);
                }

                _tagRepo.Update(obj, UpdateMode.Update);
                _tagRepo.Save();

                TempData[WC.Success] = "Тэг '" + obj.Name + "' успешно обновлен";
                return RedirectToAction("Index");
            }

            // TODO: После редактирования записи восстанавливать строку поиска в списке Index
            // TODO: После редактирования записи восстанавливать checkbox "Показывать архивные записи"
            // TODO: После редактирования записи устанавливать выбор в списке Index на отредактированную запись

            return View(obj);
        }


        //GET - DELETE
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _tagRepo.Find(id.GetValueOrDefault());

            if (id == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        //POST - DELETE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Tag obj)
        {

            if (ModelState.IsValid)
            {
                _tagRepo.Update(obj, UpdateMode.MoveToArchive);
                _tagRepo.Save();

                TempData[WC.Success] = "Тэг '" + obj.Name + "' успешно удалён в архив";
                return RedirectToAction("Index");
            }

            // TODO: После удаления записи восстанавливать строку поиска в списке Index
            // TODO: После удаления записи восстанавливать checkbox "Показывать архивные записи"
            // TODO: После удаления записи, если checkbox "Показывать архивные записи" включен, устанавливать выбор в списке Index на удалённую в архив запись


            return View(obj);


        }

        //GET - RESTORE
        public IActionResult Restore(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _tagRepo.Find(id.GetValueOrDefault());

            if (id == null)
            {
                return NotFound();
            }


            return View(obj);
        }


        //POST - Restore
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Restore(Tag obj)
        {

            if (ModelState.IsValid)
            {
                _tagRepo.Update(obj, UpdateMode.RestoreFromArchive);
                _tagRepo.Save();

                TempData[WC.Success] = "Тэг '" + obj.Name + "' успешно восстановлен из архива";
                return RedirectToAction("Index");
            }

            // TODO: После восстановления из архива записи восстанавливать строку поиска в списке Index
            // TODO: После восстановления из архива записи восстанавливать checkbox "Показывать архивные записи"
            // TODO: После восстановления из архива записи устанавливать выбор в списке Index на удалённую в архив запись


            return View(obj);

        }



        #region API CALLS
        [HttpGet]
        public IActionResult GetTagList()
        {
            return Json(new { data = _tagRepo.GetAll() });
        }
        #endregion
    }
}

ALIS/Views/Shared/_EmptyLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Печать карточек</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body>

    <div class="container body-content">
        @RenderBody()
    </div>


    @RenderSection("Scripts", required: false)

</body>
</html>

ALIS/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@using ALIS_Utility
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ALIS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/personbarcode.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/fontawersome/css/all.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.0/css/jquery.dataTables.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
    @* Syncfusion Essential JS 2 Styles *@
    <link href="~/css/syncfusion/bootstrap4.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3 navbar-fixed-top">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white-50" asp-area="" asp-controller="Book" asp-action="Index"><i class="fas fa-home"> Домой</i></a>
                            </li>

                            @if (User.IsInRole(WC.AdminRole))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
                                        <i class="fas fa-tools"></i> Администрирование
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" asp-area="" asp-controller="Person" asp-action="Index"><i class="fas fa-users"></i> Сотрудники / студенты / пользователи</a>
                                    </div>
                                </li>

                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
                                        <i class="fas fa-list"></i> Справочники
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" asp-area="" asp-controller="Author" asp-action="Index"><i class="fas fa-user-edit"></i> Авторы</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="Grif" asp-action="Index"><i class="fas fa-stamp"></i> Грифы</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="Genre" asp-action="Index"><i class="fas fa-theater-masks"></i> Жанры</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="Publisher" asp-action="Index"><i class="fas fa-building"></i> Издатели</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="AuthorType" asp-action="Index"><i class="fas fa-pen-alt"></i> Типы авторства</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="Tag" asp-action="Index"><i class="fas fa-tags"></i> Тэги</a>
                                    </div>
                                </li>

                            }

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
                                    <i class="fas fa-book-open"></i> Библиотека
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="" asp-controller="Book" asp-action="Index"><i class="fas fa-book"></i> Книги</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="BookCopy" asp-action="Index"><i class="fas fa-th-list"></i> Экземпляры</a>
                                </div>
                            </li>
                        }
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <div class="d-print-none">
                <partial name="_Notifications" />
            </div>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-dark d-print-none">
        <div class="container text-white-50">
            &copy; ALIS - <a href="http://spospk.ru/">СПК</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.0/js/jquery.dataTables.min.js"></script>
    @*<script src="https://cdn.datatables.net/plug-ins/{plugins-release-version}/i18n/Russian.json"></script>*@
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
    @* Syncfusion Essential JS 2 Scripts *@
    <script src="~/js/syncfusion/ej2.min.js"></script>

    <script>
        ej.base.L10n.load({
            'ru-RU': {
                'grid': {
                    'EmptyRecord': 'Нет данных для отображения',
                    'True': 'Истина',
                    'False': 'Ложь',
                    'InvalidFilterMessage': 'Неверные данные для фильтра',
                    'GroupDropArea': 'Перетащите сюда заголовок столбца, чтобы сгруппировать столбец',
                    'GroupDisable': 'Группировка запрещена для этой колонки',
                    'Add': 'Добавить',
                    'Edit': 'Редактировать',
                    'Cancel': 'Отмена',
                    'Update': 'Обновить',
                    'Delete': 'Удалить',
                    'Print': 'Печать',
                    'Pdfexport': 'Экспорт в PDF',
                    'Excelexport': 'Экспорт в Excel',
                    'Wordexport': 'Экспорт в Word',
                    'Csvexport': 'Экспорт в CSV',
                    'Search': 'Поиск',
                    'Columnchooser': 'Колонки',
                    'Save': 'Сохранить',
                    'EditOperationAlert': 'Нет выбранных записей для редактирования',
                    'DeleteOperationAlert': 'Нет выбранных записей для удаления',
                    'SaveButton': 'Сохранить',
                    'CancelButton': 'Отмена',
                    'EditFormTitle': 'Детали ...',
                    'AddFormTitle': 'Добавление новой записи',
                    'AddFormTitle': 'Добавление новой записи',
                    'BatchSaveConfirm': 'Сохранить изменения ?',
                    'BatchSaveLostChanges': 'Не сохранённые изменения будут потеряны. Продолжить ?',
                    'ConfirmDelete': 'Удалить запись ?',
                    'CancelEdit': 'Отменить изменения ?',
                    'ChooseColumns': 'Выбрать столбцы',
                    'SearchColumns': 'Столбцы для поиска',
                    'Matchs': 'Совпадений не найдено',
                    'FilterButton': 'Фильтр',
                    'ClearButton': 'Очистить',
                    'StartsWith': 'Начинается с',
                    'EndsWith': 'Заканчивается строкой',
                    'Contains': 'Содержит',
                    'Equal': 'Равно',
                    'NotEqual': 'Не равно',
                    'LessThan': 'Меньше',
                    'LessThanOrEqual': 'Меньше или равно',
                    'GreaterThan': 'Больше',
                    'GreaterThanOrEqual': 'Больше или равно',
                    'ChooseDate': 'Выбрать дату',
                    'EnterValue': 'Ввести значение',
                    'Copy': 'Копировать',
                    'Group': 'Группировать по этому столбцу',
                    'autoFitAll': 'Автоширина для всех колонок',
                    'autoFit': 'Автоширина для этой колонки',
                    'Export': 'Экспорт',
                    'FirstPage': 'Первая страница',
                    'LastPage': 'Последняя страница',
                    'NextPage': 'Следующая страница',
                    'SortAscending': 'Упорядочить по возрастанию',
                    'SortDescending': 'Упорядочить по убыванию',
                    'EditRecord': 'Редактировать запись',
                    'DeleteRecord': 'Удалить запись',
                    'FilterMenu': 'Фильтр',
                    'SelectAll': 'Выбрать все',
                    'Blanks': 'Пустые',
                    'FilterTrue': 'Да',
                    'FilterFalse': 'Нет',
                    'NoResult': 'Совпадений не найдено',
                    'ClearFilter': 'Очистить фильтр',
                    'NumberFilter': 'Числовые фильтры',
                    'TextFilter': 'Текстовые фильтры',
                    'DateFilter': 'Фильтр по дате',
                    'MatchCase': 'Учитывать регистр',
                    'Between': 'Между',
                    'CustomFilter': 'Пользовательский фильтр',
                    'CustomFilterPlaceHolder': 'Ввести значение',
                    'CustomFilterDatePlaceHolder': 'Выбрать дату',
                    'AND': 'И',
                    'OR': 'ИЛИ',
                    'ShowRowsWhere': 'Показать строки где ...',
                    'currentPageInfo': '{0} из {1} страниц',
                    'totalItemsInfo': '({0} записей)',
                    'firstPageTooltip': 'Перейти на первую страницу',
                    'lastPageTooltip': 'Перейти на последнюю страницу',
                    'nextPageTooltip': 'Перейти на следующую страницу',
                    'previousPageTooltip': 'Перейти на предыдущую страницу',
                    'nextPagerTooltip': 'Перейти на следующую страницу',
                    'previousPagerTooltip': 'Перейти на предыдущую страницу',
                    'pagerDropDown': 'Записей на странице',
                    'pagerAllDropDown': 'Все записи',
                    'All': 'Все',
                    'UnGroup': 'Нажмите, чтобы разгруппировать',
                    'EmptyDataSourceError': 'DataSource не должен быть пустым при первой загрузке, так как столбцы из dataSource в сетке столбцов AutoGenerate',
                    'Item': 'Элемент',
                    'Items': 'Элементы',
                    'FilterbarTitle': ' - фильтр'
                }
                ,
                'pager': {
                    'currentPageInfo': '{0} из {1} страниц',
                    'totalItemsInfo': '({0} строк)',
                    'firstPageTooltip': 'На первую страницу',
                    'lastPageTooltip': 'На последнюю страницу',
                    'nextPageTooltip': 'На следующую страницу',
                    'previousPageTooltip': 'Перейти на пердыдущую страницу',
                    'nextPagerTooltip': 'Петейти на следующую страницу',
                    'previousPagerTooltip': 'Перейти на предыдущую страницу'
                }
            }
        });
    </script>


    @await RenderSectionAsync("Scripts", required: false)
    <ejs-scripts></ejs-scripts>
</body>
</html>